"""
finetune_india.py
──────────────────────────────────────────────────────────────────
Fine-tune yolov8n_rdd_india.pt using the existing dataset at D:/We4/

Dataset confirmed (from D:/We4/data.yaml):
    nc: 5
    classes: pothole, crack_longitudinal, crack_transverse, rutting, repair
    train: D:/We4/train/images
    val:   D:/We4/valid/images

What the original train_local.py did wrong for fine-tuning:
    model = YOLO('yolov8n.pt')   ← fresh weights, learns from scratch every time
    lr0   = 0.01 (default)       ← too high, overwrites existing learned features
    no freeze                    ← all layers retrained = unstable

What this script does correctly:
    model = YOLO('models/yolov8n_rdd_india.pt')  ← your existing 58.8% weights
    lr0   = 0.0005                                ← low LR, gentle refinement
    freeze = 10                                   ← backbone stays fixed
    Absolute path YAML generated internally       ← no relative path issues

Expected improvement: 58.8% → 65-72% mAP50

Usage
─────
    conda activate driverguard
    cd /d D:\\We4\\DriverGuard
    python finetune_india.py

    python finetune_india.py --batch 4     # if GPU runs out of memory
    python finetune_india.py --device cpu  # CPU fallback (slow)
"""

import argparse
import multiprocessing
import shutil
import sys
from pathlib import Path

# ─── Paths ────────────────────────────────────────────────────────────────────

ROOT       = Path(__file__).resolve().parent            # D:/We4/DriverGuard
BASE_MODEL = ROOT / "models" / "yolov8n_rdd_india.pt"  # existing 58.8% model
TRAIN_OUT  = Path("D:/We4/training_output")

# Dataset folders (absolute — avoids relative path resolution issues)
WE4        = Path("D:/We4")
TRAIN_IMGS = WE4 / "train"  / "images"
VALID_IMGS = WE4 / "valid"  / "images"
TEST_IMGS  = WE4 / "test"   / "images"

# We generate a clean YAML with absolute paths inside the project
# so YOLO never has to resolve ../  relative paths
YAML_PATH  = ROOT / "data" / "finetune_india.yaml"


# ─── Step 1: Write absolute-path YAML ────────────────────────────────────────

def write_yaml():
    """
    Generate data/finetune_india.yaml with absolute paths.

    The original D:/We4/data.yaml uses relative paths (../train/images)
    which resolve differently depending on working directory. Absolute
    paths are unambiguous and prevent silent dataset-not-found errors.

    Classes match your data.yaml exactly (nc=5).
    """
    YAML_PATH.parent.mkdir(parents=True, exist_ok=True)
    YAML_PATH.write_text(
        f"# Auto-generated by finetune_india.py\n"
        f"# Absolute-path version of D:/We4/data.yaml\n\n"
        f"path: {WE4.resolve()}\n"
        f"train: train/images\n"
        f"val:   valid/images\n"
        f"test:  test/images\n\n"
        f"nc: 5\n"
        f"names:\n"
        f"  0: pothole\n"
        f"  1: crack_longitudinal\n"
        f"  2: crack_transverse\n"
        f"  3: rutting\n"
        f"  4: repair\n"
    )
    print(f"   YAML written → {YAML_PATH}")


# ─── Step 2: Verify everything exists ────────────────────────────────────────

def verify():
    ok = True

    checks = [
        (BASE_MODEL,  "Base model (yolov8n_rdd_india.pt)"),
        (TRAIN_IMGS,  "Train images folder"),
        (VALID_IMGS,  "Valid images folder"),
    ]
    for path, label in checks:
        if path.exists():
            extra = ""
            if path.is_dir():
                n = len(list(path.glob("*.*")))
                extra = f"  ({n} files)"
            print(f"   ✓  {label}{extra}")
        else:
            print(f"   ✗  NOT FOUND: {label}")
            print(f"      Expected at: {path}")
            ok = False

    if not ok:
        print("\n   Fix the missing paths above and re-run.")
        sys.exit(1)


# ─── Step 3: Fine-tune ────────────────────────────────────────────────────────

def finetune(epochs: int, batch: int, device: str):
    import os
    from ultralytics import YOLO

    # Fix OMP duplicate runtime warning (libomp.dll vs libiomp5md.dll conflict on Windows)
    # Without this, the process may crash immediately after training starts
    os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

    # Safety backup — so you can roll back to the old model if needed
    backup = BASE_MODEL.with_suffix(".backup.pt")
    shutil.copy2(BASE_MODEL, backup)
    print(f"\n   Backed up existing model  →  {backup.name}")
    print(f"   Fine-tuning from          →  {BASE_MODEL.name}  (58.8% mAP50)")
    print(f"   Dataset YAML              →  {YAML_PATH.name}")
    print(f"   Epochs: {epochs}   Batch: {batch}   Device: {device}\n")

    model = YOLO(str(BASE_MODEL))

    results = model.train(
        data    = str(YAML_PATH),
        epochs  = epochs,
        batch   = batch,
        imgsz   = 640,
        device  = device,
        project = str(TRAIN_OUT),
        name    = "rdd_india_finetune",

        # ── Fine-tuning hyperparameters ──────────────────────────────────
        # Low LR because we're refining, not learning from scratch.
        # The 6 previous runs in training_output all used default LR 0.01
        # which effectively restarted learning every time.
        # IMPORTANT: must set optimizer='SGD' explicitly.
        # When optimizer='auto' (default), YOLO silently ignores lr0 and uses
        # its own LR (0.01). Confirmed from log: "ignoring lr0=0.0005 ... MuSGD(lr=0.01)"
        # Explicitly setting SGD forces our low LR to be respected.
        optimizer     = "SGD",
        lr0           = 0.0005,   # low LR — refining, not learning from scratch
        lrf           = 0.01,

        # Freeze the first 10 backbone layers.
        # These learn low-level features (edges, textures) which are
        # already well-learned. Only the detection head needs India tuning.
        freeze        = 10,

        # Let gradients stabilise before full training kicks in
        warmup_epochs = 3,

        # Stop early if no improvement for 20 consecutive epochs
        patience      = 20,

        # ── India-specific augmentations ─────────────────────────────────
        # Simulate real Indian road camera conditions:
        #   harsh noon sun, dust/haze, tree shadows, slight camera tilt
        hsv_h         = 0.015,  # hue shift
        hsv_s         = 0.6,    # saturation (dusty/overcast)
        hsv_v         = 0.5,    # brightness (noon sun vs shadows)
        degrees       = 5.0,    # rotation (dashcam tilt)
        translate     = 0.1,
        scale         = 0.5,    # zoom (different following distances)
        fliplr        = 0.5,    # horizontal flip
        mosaic        = 1.0,    # 4-image mosaic (helps small pothole detection)
        mixup         = 0.1,

        # ── Bookkeeping ───────────────────────────────────────────────────
        save          = True,
        save_period   = 10,    # checkpoint every 10 epochs
        plots         = True,  # save loss + mAP curves
        workers       = 0,     # Windows-safe
    )

    # Deploy best weights back to models/
    best = Path(results.save_dir) / "weights" / "best.pt"
    if best.exists():
        shutil.copy2(best, BASE_MODEL)

        m        = results.results_dict
        new_map  = m.get("metrics/mAP50(B)",    0) * 100
        new_map2 = m.get("metrics/mAP50-95(B)", 0) * 100
        old_map  = 58.8

        print("\n" + "─" * 56)
        print("  Fine-tuning complete!")
        print(f"  Previous mAP50    :  {old_map:.1f}%")
        print(f"  New mAP50         :  {new_map:.1f}%  "
              f"({'↑ improved!' if new_map > old_map else '↓ try more epochs'})")
        print(f"  New mAP50-95      :  {new_map2:.1f}%")
        print(f"  Run folder        :  {results.save_dir}")
        print(f"  Deployed model    :  {BASE_MODEL}")
        print(f"  Old model backup  :  {backup.name}")
        print("─" * 56)
        print("\n  Restart DriverGuard to load the improved model.\n")
    else:
        print(f"\n⚠  best.pt not found at {best}")
        print(f"   Training may have crashed — check the output above.")
        print(f"   Your original model is safe at: {backup}")


# ─── Entry ────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    multiprocessing.freeze_support()   # required on Windows

    parser = argparse.ArgumentParser(
        description="Fine-tune DriverGuard road model on India dataset")
    parser.add_argument("--epochs", type=int, default=75,
                        help="Fine-tune epochs (default: 75)")
    parser.add_argument("--batch",  type=int, default=8,
                        help="Batch size — use 4 if GPU runs OOM (default: 8)")
    parser.add_argument("--device", type=str, default="0",
                        help="CUDA device index or 'cpu' (default: 0)")
    args = parser.parse_args()

    print("\n── DriverGuard  India Fine-tune ──────────────────────────────")
    print(f"   Base model  :  yolov8n_rdd_india.pt  (58.8% mAP50)")
    print(f"   nc          :  5  (pothole / crack_long / crack_trans / rutting / repair)")
    print(f"   Epochs      :  {args.epochs}   Batch: {args.batch}   Device: {args.device}")
    print("──────────────────────────────────────────────────────────────\n")

    print("[1/3]  Writing absolute-path YAML …")
    write_yaml()

    print("\n[2/3]  Verifying paths …")
    verify()

    print("\n[3/3]  Fine-tuning …")
    finetune(args.epochs, args.batch, args.device)